regions:
  - us-east-1
images:
  - id: windows22-docker-hyperv-x64
    volume_size: 50
    source_ami_name: runs-on-v2.2-windows22-full-x64-*
    source_ami_owner: 135269210855
    description: HeroDevs Windows 2022 with Docker and Hyper-V x64
